services:
  - type: web
    name: v1webdesign
    env: static
    buildCommand: echo "Static site - no build required"
    staticPublishPath: .
    domains:
      - v1webdesign.com
      - www.v1webdesign.com
    headers:
      - path: /*
        name: X-Frame-Options
        value: DENY
      - path: /*
        name: X-Content-Type-Options
        value: nosniff
      - path: /*
        name: Referrer-Policy
        value: strict-origin-when-cross-origin
      - path: /*
        name: Permissions-Policy
        value: camera=(), microphone=(), geolocation=()
      - path: "*.css"
        name: Cache-Control
        value: public, max-age=31536000
      - path: "*.js"
        name: Cache-Control
        value: public, max-age=31536000
      - path: "*.png"
        name: Cache-Control
        value: public, max-age=31536000
      - path: "*.jpg"
        name: Cache-Control
        value: public, max-age=31536000
      - path: "*.jpeg"
        name: Cache-Control
        value: public, max-age=31536000
      - path: "*.webp"
        name: Cache-Control
        value: public, max-age=31536000
      - path: "*.svg"
        name: Cache-Control
        value: public, max-age=31536000
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: NODE_ENV
        value: production